AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0230bd60aa48260c6" # Change to your desired AMI ID
      InstanceType: "t2.micro"         # Change to your desired instance type
      KeyName: "terraform"         # Change to your key pair name

      Tags:
        - Key: "Name"
          Value: "MyEC2Instance"
