name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Change to your desired AWS region
      
    - name: Print template file contents
      run: |
        cat website.yml    

    - name: Fetch CloudFormation events
      run: aws cloudformation describe-stack-events --stack-name MyEC2Stack
      

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --stack-name MyEC2Stack \
          --template-file website.yml \
          --capabilities CAPABILITY_IAM



      









      

